language: python

stages:
  - linting
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

install:
  - pip install pip -U
  - which pip
  - which python
  - which python3
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py -o get-poetry.py
  - python3 get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - which python
  - which poetry
  - which pip
  - poetry show --tree
  - poetry install -vvv

script: pytest -q --runslow tests/

jobs:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial

    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
